### ISSUE TITLE
jenkins-plugins问题

### ISSUE THREAD

**Issue by GeorgeGeng** [FollowmeTech/jenkins-cicd#4]
作者你好，我在使用参考您的代码过程中，发现一个问题，getting-start.md
里面的install jenkins-plugins的bash [./tools/bulter ]butler plugins import --server localhost:8080 --username admin --password admin这一行，不知道是怎么使用？bulter不能bash运行，并且也不能被Jenkins识别为插件，是否可以麻烦解答一下。

**Comment by hoyho** [comment]
> 作者你好，我在使用参考您的代码过程中，发现一个问题，getting-start.md
> 里面的install jenkins-plugins的bash [./tools/bulter ]butler plugins import --server localhost:8080 --username admin --password admin这一行，不知道是怎么使用？bulter不能bash运行，并且也不能被Jenkins识别为插件，是否可以麻烦解答一下。

`bash path_to_your_bulter plugins import --server localhost:8080 --username admin --password admin`
这是为了导入plugins.txt中所有的jenkins插件，butler是一个golang写的导入工具，参考[https://github.com/mlabouardy/butler](https://github.com/mlabouardy/butler),命令无法识别是因为butler需要安装，具体安装方式取决于你的平台，你可以参考说明文档[install_butler](https://github.com/mlabouardy/butler#linux)安装，

这里可能需要注意下你当前目录，因为./tools/bulter 表示指定了当前目录下的tools下的bulter而不需要另外下载（默认你是使用Linux，且pwd是repo的根目录）

**Comment by GeorgeGeng** [comment]
谢谢！建议在readme里加上一下，萌新容易懵。

**Comment by lincuss** [comment]
默认是不需要安装的

**Comment by lincuss** [comment]
./tools/bulter 是可以直接运行的 
需要指向权限而已
1. 给./tools/bulter设置执行权限
2. 运行./tools/bulter plugins import --server localhost:8080 --username admin --password admin  即可
