### ISSUE TITLE
传入容器启动命令

### ISSUE THREAD

**Issue by GeorgeGeng** [FollowmeTech/jenkins-cicd#5]
作者你好，我使用您这份代码的时候，需要我们传入一个容器启动命令，而不是使用dockerfile里面的命令，我用的portainer版本为1.20，修改您的接口如下，但是命令没有运行，请问您用的portainer的API应该怎么怎么写？
这是构造的payload：
{"Env": ["ASPNETCORE_ENVIRONMENT=Development"], "Image": "10.65.65.199:4000/web_app:ttt", "ExposedPorts": {"8000/tcp": {}}, "HostConfig": {"NetworkMode": "bridge", "PortBindings": {"8000/tcp": [{"HostIp": "", "HostPort": "8001"}]}, "RestartPolicy": {"Name": "always", "MaximumRetryCount": 0}}, "Command": "bash web_svc_start.sh --broker-url 127.0.0.1:5672 --backend-url 127.0.0.1:30379 --Port 8000"}

**Comment by hoyho** [comment]
> 作者你好，我使用您这份代码的时候，需要我们传入一个容器启动命令，而不是使用dockerfile里面的命令，我用的portainer版本为1.20，修改您的接口如下，但是命令没有运行，请问您用的portainer的API应该怎么怎么写？
> 这是构造的payload：
> {"Env": ["ASPNETCORE_ENVIRONMENT=Development"], "Image": "10.65.65.199:4000/web_app:ttt", "ExposedPorts": {"8000/tcp": {}}, "HostConfig": {"NetworkMode": "bridge", "PortBindings": {"8000/tcp": [{"HostIp": "", "HostPort": "8001"}]}, "RestartPolicy": {"Name": "always", "MaximumRetryCount": 0}}, "Command": "bash web_svc_start.sh --broker-url 127.0.0.1:5672 --backend-url 127.0.0.1:30379 --Port 8000"}

@GeorgeGeng 
具体命令是怎么传， 你可以debug下:
debug 方法：
`sudo strace -e write -o /tmp/docker.strace -s 10000 -f your_cmd_to_start_container`
然后`cat /tmp/docker.strace`就可以看到具体的参数名称和格式，**按照此格式**修改接口即可

大概看了下，payload命令这部分应该是类似"Cmd":["echo","1"]这样

![image](https://user-images.githubusercontent.com/8370967/51725056-41f36280-209b-11e9-8c9f-e5f1821cedb2.png)

**Comment by GeorgeGeng** [comment]
niupi,已经搞定了，我看了portainer源码找到了应该是Cmd。你这个代码我用的时候还遇到的问题也在这跟您提一下。一个是在config.loadconfig()里面的判断，源码用的大写，导致一直匹配失败抛异常，应该为小写。    if env not in ["dev","beta","prod"]:
        raise Exception("unknow config [{}], only support[dev/beta/prod]".format(env))
二是在pubproxy.create_container()里面，        if self.port:
            ports = self.port.split(":")    #-p 6666:80
            port_setting = {
                ports[1]+"/tcp": [{"HostIp": "", "HostPort": ports[0]}]
            }  # {"80/tcp":[{"HostIp":"","HostPort":"8585"}
如果不传入port导致ports为空，接下来的payload会报错。

感谢大佬的及时回复！提前祝你新年快乐吧！
